In [1]:
import numpy as np

In [7]:
x=np.array([[[2,2],[2,3]]]).size
x

4

# np.array(object,dtype)

### Inspecting the properties of Numpy array

In [2]:
x = np.arange(10) #1D
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
y = np.array([[[12,3,5],[5,66,7],[1,0,69]]])
y 
#2D

array([[[12,  3,  5],
        [ 5, 66,  7],
        [ 1,  0, 69]]])

In [4]:
#check number of  elementts
x.size

10

In [5]:
y.size

9

In [6]:
len(x) #gives total elements as array is 1D

10

In [7]:
len(y) #give num of rows as array is 2D

3

In [8]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
y

array([[12,  3,  5],
       [ 5, 66,  7],
       [ 1,  0, 69]])

In [10]:
# if we want to check no. of rows and columns
x.shape

(10,)

In [ ]:
#(10,) 1D
#(2,3) 2D
xx

In [11]:
y.shape

(3, 3)

### data type

In [14]:
x.dtype

dtype('int32')

In [15]:
y.dtype

dtype('int32')

In [19]:
#at the time of creation if i want to change dtype then
np.array([10,20],dtype='complex')

array([10.+0.j, 20.+0.j])

In [20]:
#but if after creation of an array i want to change dtype then???
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#change dtype of x
x.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
x.astype('float32')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [23]:
x.astype('f4')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [25]:
x.astype(np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## How to check all methods and properties supported by numpy

In [26]:
print(dir(x))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [ ]:
# 'tobytes', 'tofile', 'tolist', 'tostring'
# when we want to covnert array in to anther type then use above options

In [27]:
y

array([[12,  3,  5],
       [ 5, 66,  7],
       [ 1,  0, 69]])

In [28]:
type(y)

numpy.ndarray

In [10]:
#convert into a list
y.tolist()

[[[12, 3, 5], [5, 66, 7], [1, 0, 69]]]

In [11]:
list(y)

[array([[12,  3,  5],
        [ 5, 66,  7],
        [ 1,  0, 69]])]

In [32]:
# can we create a dict from an array???
y

array([[12,  3,  5],
       [ 5, 66,  7],
       [ 1,  0, 69]])

In [33]:
dict(y)

ValueError: dictionary update sequence element #0 has length 3; 2 is required

# Numpy operations: stat + math

In [34]:
y

array([[12,  3,  5],
       [ 5, 66,  7],
       [ 1,  0, 69]])

## np.sum()

In [35]:
np.sum(y) #total addition

168

In [13]:
# rowwise addition
np.sum(y,axis= 1)

array([[18, 69, 81]])

In [12]:
# columnwise addition
np.sum(y,axis= 0)

array([[12,  3,  5],
       [ 5, 66,  7],
       [ 1,  0, 69]])

## np.mean()

In [14]:
y

array([[[12,  3,  5],
        [ 5, 66,  7],
        [ 1,  0, 69]]])

In [40]:
np.mean(y)

18.666666666666668

In [ ]:
#Assignment:  rowwise + columnwise

In [41]:
#np.median()
#np.min()
#np.max()

In [15]:
np.median(y)

5.0

In [17]:
np.min(y)

0

In [18]:
np.max(y)

69