# Numpy 

In [1]:
# import numpy
import numpy

In [2]:
# check numpy version
numpy.__version__

'1.23.3'

In [3]:
#lets create a numpy  array
numpy.array([1,2,3])

array([1, 2, 3])

In [4]:
# make it simple: use module aliasing
import numpy as np

In [6]:
a = np.array([10,20,30])
a

array([10, 20, 30])

In [7]:
b = [10,20,30]
b

[10, 20, 30]

In [10]:
a * 3 #elementwise multiplication

array([30, 60, 90])

In [11]:
b * 3 # b is list: it will perform repettition

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [13]:
#check size of a and b
print('Array:',a.__sizeof__())
print('List:',b.__sizeof__())

Array: 116
List: 104


In [15]:
a*200*350

array([ 700000, 1400000, 2100000])

In [19]:
%%time
for i in range(1000):
    print(a*100)

[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 300

[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 300

In [20]:
%%time
for i in range(1000):
    print(b)

[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]

# Creation of array

In [21]:
np.array([1,2,3])

array([1, 2, 3])

In [22]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

np.array(object,dtype)

In [4]:
numpy.array(100)

array(100)

In [27]:
np.array([100,200])

array([100, 200])

In [28]:
#1D array
np.array([12,3,4,6])

array([12,  3,  4,  6])

In [29]:
#check dimension of array
np.array([12,3,4,6]).ndim

1

In [30]:
#2D
np.array([[1,2],[4,5]])

array([[1, 2],
       [4, 5]])

In [31]:
#check dimension
np.array([[1,2],[4,5]]).ndim

2

In [33]:
#3D array: is made up of 2D array
c = np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
c

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [34]:
c.ndim

3

In [35]:
c.shape

(2, 2, 2)

In [41]:
np.array([12,'3',34.6675675])

array(['12', '3453453543453534534534534534534534534535345', '34.6675675'],
      dtype='<U43')

In [39]:
np.array(['Ramesh','Suresh'])
# if we give str or hetro. data then its data type is unicode

array(['Ramesh', 'Suresh'], dtype='<U6')

In [43]:
# what is type of numpy array
type(c)

numpy.ndarray

In [ ]:
# Features of Numpy
# Sequence order is preserved
# indexing supported
# slicing supported
# homo. hetro value accepted

## -------------------------------------------------------

In [46]:
# other options for creating a numpy array
# arange of numpy is same as that of range in python
np.arange(5)

array([0, 1, 2, 3, 4])

In [47]:
np.arange(100,106)

array([100, 101, 102, 103, 104, 105])

In [48]:
np.arange(100,0,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [51]:
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [52]:
# create an array with all ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [54]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [55]:
np.ones((3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])