# Numpy ---> Numerical Python
* NumPy is a Python library used for working with arrays.



## Create a numpy array

In [1]:
import numpy as np

In [2]:
np.array([10,20,30])

array([10, 20, 30])

In [3]:
a = np.array([20,30,40])

In [4]:
a.ndim

1

In [6]:
b = np.array([[1,2,3],[4,5,6]])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b.ndim

2

In [9]:
np.array([[[1,2]],[[4,6]]])

array([[[1, 2]],

       [[4, 6]]])

In [10]:
np.array([[[1,2]],[[4,6]]]).ndim

3

In [11]:
np.array([[[1,2]],[[4,6]]]).shape

(2, 1, 2)

In [12]:
b.shape

(2, 3)

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6]])

### Why array is faster than list?
* Numpy arrays have fixed size 

In [14]:
arr = np.arange(100000)

In [15]:
python_list = list(range(100000))

In [17]:
%time for j in range(10) : [i*3 for i in python_list]

CPU times: total: 141 ms
Wall time: 142 ms


In [18]:
%time for j in range(10) : arr = arr*3

CPU times: total: 0 ns
Wall time: 998 µs


## Check some properties of an array

In [19]:
ar = np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
ar

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [20]:
# check dimension
ar.ndim

3

In [21]:
# check total blocks , rows and colums
ar.shape

(2, 2, 2)

In [22]:
# if i want to check total number of elements
ar.size

8

In [23]:
#how much bytes alocated to each element
ar.itemsize

4

## Creation of numpy array using numpy functions

In [24]:
# array with all values 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# array with all values 1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
# change the dtype
a = np.ones((2,2,2),dtype='int')
a

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [29]:
a.dtype

dtype('int32')

In [30]:
b = np.ones((2,2,2),dtype='int8')
b

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [31]:
a.__sizeof__()

168

In [32]:
b.__sizeof__()

144

In [33]:
b.itemsize

1

In [ ]:
#check the difference between int32 & int8


In [34]:
# array with specified value
np.full((3,3),fill_value=100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [35]:
np.full((3,3),fill_value='py')

array([['py', 'py', 'py'],
       ['py', 'py', 'py'],
       ['py', 'py', 'py']], dtype='<U2')

In [36]:
np.array([1,2,2.0])

array([1., 2., 2.])

In [37]:
np.array([1,2,'py'])

array(['1', '2', 'py'], dtype='<U11')

### arange()

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [41]:
np.arange(-10,1)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [42]:
np.arange(10,-1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### linspace()

In [16]:
# used to generate linearly spaced values
# with homogeneous spacing
# equal spacing btween 2 consecutive elements 

In [43]:
np.linspace(1,21)

array([ 1.        ,  1.40816327,  1.81632653,  2.2244898 ,  2.63265306,
        3.04081633,  3.44897959,  3.85714286,  4.26530612,  4.67346939,
        5.08163265,  5.48979592,  5.89795918,  6.30612245,  6.71428571,
        7.12244898,  7.53061224,  7.93877551,  8.34693878,  8.75510204,
        9.16326531,  9.57142857,  9.97959184, 10.3877551 , 10.79591837,
       11.20408163, 11.6122449 , 12.02040816, 12.42857143, 12.83673469,
       13.24489796, 13.65306122, 14.06122449, 14.46938776, 14.87755102,
       15.28571429, 15.69387755, 16.10204082, 16.51020408, 16.91836735,
       17.32653061, 17.73469388, 18.14285714, 18.55102041, 18.95918367,
       19.36734694, 19.7755102 , 20.18367347, 20.59183673, 21.        ])

In [44]:
1.40816327 - 1

0.40816326999999997

In [45]:
np.linspace(1,25,num=20)

array([ 1.        ,  2.26315789,  3.52631579,  4.78947368,  6.05263158,
        7.31578947,  8.57894737,  9.84210526, 11.10526316, 12.36842105,
       13.63157895, 14.89473684, 16.15789474, 17.42105263, 18.68421053,
       19.94736842, 21.21052632, 22.47368421, 23.73684211, 25.        ])

In [51]:
np.linspace(1,25,20,retstep = True)

(array([ 1.        ,  2.26315789,  3.52631579,  4.78947368,  6.05263158,
         7.31578947,  8.57894737,  9.84210526, 11.10526316, 12.36842105,
        13.63157895, 14.89473684, 16.15789474, 17.42105263, 18.68421053,
        19.94736842, 21.21052632, 22.47368421, 23.73684211, 25.        ]),
 1.263157894736842)

In [52]:
2.26315789 - 1

1.26315789

In [53]:
np.linspace(1,25,20,retstep = True,endpoint=False)

(array([ 1. ,  2.2,  3.4,  4.6,  5.8,  7. ,  8.2,  9.4, 10.6, 11.8, 13. ,
        14.2, 15.4, 16.6, 17.8, 19. , 20.2, 21.4, 22.6, 23.8]),
 1.2)

# Shape manipulation

In [2]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
a.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [58]:
a.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [3]:
import numpy as np
a.reshape(6,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
a.reshape(-1,5)

ValueError: cannot reshape array of size 24 into shape (5)

In [61]:
a.resize(4,6)

In [62]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [63]:
a.resize(4,-1)

ValueError: negative dimensions not allowed

In [66]:
a.shape = (6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Convert ND array to 1D

In [67]:
ar

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [68]:
ar.ravel()

array([1, 2, 3, 4, 6, 7, 8, 9])

In [69]:
ar.flatten()

array([1, 2, 3, 4, 6, 7, 8, 9])

In [70]:
c = ar.ravel()
c

array([1, 2, 3, 4, 6, 7, 8, 9])

In [72]:
c[0] = 100

In [73]:
c

array([100,   2,   3,   4,   6,   7,   8,   9])

In [75]:
ar

array([[[100,   2],
        [  3,   4]],

       [[  6,   7],
        [  8,   9]]])

In [76]:
d = ar.flatten()
d

array([100,   2,   3,   4,   6,   7,   8,   9])

In [77]:
d[0] = 200

In [78]:
d

array([200,   2,   3,   4,   6,   7,   8,   9])

In [79]:
ar

array([[[100,   2],
        [  3,   4]],

       [[  6,   7],
        [  8,   9]]])

# transpose(): convert row as column and vice-versa

In [80]:
s = np.arange(24).reshape(4,6)

In [81]:
s

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [82]:
s.T

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [83]:
np.transpose(s)

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [84]:
# Identity matrix

In [85]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])