In [3]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [4]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## add element in array

In [5]:
'''
Signature: np.append(arr, values, axis=None)
Docstring:
Append values to the end of an array.
'''
np.append(a,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
np.append(a,[12,13,14,15])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
#add 1 row
np.append(a,[[12,13,14]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [18]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
# add 1 column
np.append(a,[[12],[13],[14],[15]],axis=1)

array([[ 0,  1,  2, 12],
       [ 3,  4,  5, 13],
       [ 6,  7,  8, 14],
       [ 9, 10, 11, 15]])

In [21]:
"""
np.delete(arr, obj/index, axis=None)
Docstring:
Return a new array with sub-arrays along an axis deleted. For a one
dimensional array, this returns those entries not returned by
"""
np.delete(a,2)


array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
# delete row
np.delete(a,-1,axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
#delete column
np.delete(a,-1,axis=1)

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])

## Concatenate

In [26]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
b = np.array([[0,0,0]])
b

array([[0, 0, 0]])

In [28]:
# concat a and b: along row operation performed
np.concatenate((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  0,  0]])

In [29]:
# columnwise concatenate
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
c = np.array([[0],[0],[0],[0]])
c

array([[0],
       [0],
       [0],
       [0]])

In [31]:
np.concatenate((a,c),axis=1)

array([[ 0,  1,  2,  0],
       [ 3,  4,  5,  0],
       [ 6,  7,  8,  0],
       [ 9, 10, 11,  0]])

# Till now axis= 0 means row
# and axis= 1 means column

# insert

In [32]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
np.insert(a,2,100)

array([  0,   1, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [34]:
np.insert(a,-1,-10)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, -10,  11])

In [35]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
# add a row between 3 n 6
np.insert(a,2,[[-1,-2,-3]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [-1, -2, -3],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#Assignment:  Add a new column before last column

# Spliting of array

In [4]:
x = np.arange(24).reshape(6,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
# Split an array into multiple sub-arrays as views into `ary`.
np.split(x,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [44]:
np.split(x,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [53]:
# Split an array into multiple sub-arrays vertically (row-wise).
np.vsplit(x,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [49]:
# Split an array into multiple sub-arrays horizontally (column-wise).
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [5]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
np.vsplit(x,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [56]:
x1,y1 = np.vsplit(x,2)

In [57]:
x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
y1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# np.where

In [6]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
# Return elements chosen from `x` or `y` depending on `condition`.
# its condition based
np.where(x>10,1,0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [11]:
np.where(x>=10,1,0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [65]:
np.where(x>10,x,0)

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [66]:
gen = np.array(['Male','Female','Male','Female'])
gen

array(['Male', 'Female', 'Male', 'Female'], dtype='<U6')

In [67]:
# convert male to 0 and female to 1
np.where(gen == 'Male',0,1)
# when we have a column with binary(2) inputs
# and we need to convert as per the condition then use where

array([0, 1, 0, 1])

In [68]:
temp = [45,38,40,18,30,22,25,19]
# temp >30 set as High else low
np.where(np.temp>30,'High','Low')

TypeError: '>' not supported between instances of 'list' and 'int'