In [1]:
import numpy as np

## Shape manipulation of numpy array

# reshape()

In [2]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
#1D==> 2D (row,column)
#(4,6)(6,4)(2,12),(12,2)(3,8),(8,3),(1,24),(24,1)
np.arange(24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [5]:
a.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [6]:
#if u check original a:its unchaged
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
b = a.reshape(2,12)

In [8]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [9]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
# now lets temp. convert b into 1D
b.reshape(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
# a into 3D
a.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## if we want the changes inplace: mutable

### resize()

In [13]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
a.resize(2,12)

In [15]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [16]:
a.shape

(2, 12)

### Using shape property 

In [17]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
a.shape

(2, 12)

In [19]:
a.shape = (24,)

In [20]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
a.shape = (3,2,4)

In [22]:
a.shape

(3, 2, 4)

In [23]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

# ND array ===> convert into 1D

In [25]:
a.ndim

3

## ravel()

In [26]:
#Return a flattened array.
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [28]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

## flatten()

In [29]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
#Return a copy of the array collapsed into one dimension.
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
#Q. Difference between ravel and flatten????

In [33]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [34]:
id(b)

2782987384464

In [35]:
id(b.ravel())

2783008765104

In [39]:
id(b.flatten())

2783008766832

In [40]:
c = b.ravel()
print(c)
print(id(c))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2783008765680


In [41]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [43]:
c[0] = 100

In [44]:
c

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [45]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]])

In [46]:
id(c),id(b)

(2783008765680, 2782987384464)

In [47]:
d = b.flatten()
d

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [48]:
d[0] = -1

In [49]:
d

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]])

In [51]:
c

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [52]:
id(b),id(d)

(2782987384464, 2783008767600)

In [ ]:
# ravel creates a view of an array
# flatten creates a copy of an array

### transpose() convert row to column and viceversa

In [54]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]])

In [55]:
b.shape

(2, 12)

In [56]:
b.T

array([[100,  12],
       [  1,  13],
       [  2,  14],
       [  3,  15],
       [  4,  16],
       [  5,  17],
       [  6,  18],
       [  7,  19],
       [  8,  20],
       [  9,  21],
       [ 10,  22],
       [ 11,  23]])

In [57]:
b.T.shape

(12, 2)

In [58]:
np.transpose(b)

array([[100,  12],
       [  1,  13],
       [  2,  14],
       [  3,  15],
       [  4,  16],
       [  5,  17],
       [  6,  18],
       [  7,  19],
       [  8,  20],
       [  9,  21],
       [ 10,  22],
       [ 11,  23]])

## Scalar mathematics

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]])

#### numpy array supports elementwise addition

In [61]:
b + 100

array([[200, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123]])

In [62]:
np.add(b,100)

array([[200, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123]])

In [ ]:
# + - * / % ** //

In [63]:
b % 5

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1],
       [2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3]], dtype=int32)

In [65]:
np.multiply(b,10)

array([[1000,   10,   20,   30,   40,   50,   60,   70,   80,   90,  100,
         110],
       [ 120,  130,  140,  150,  160,  170,  180,  190,  200,  210,  220,
         230]])

## Vector math

In [91]:
x = np.array([[1,2],[2,3]])
y = np.array([[3,4]])

In [87]:
x

array([[1, 2],
       [2, 3]])

In [88]:
y

array([[3, 4, 1]])

In [69]:
x + y

array([[4, 6],
       [5, 7]])

In [73]:
np.add(x,y)

array([[4, 6],
       [5, 7]])

In [74]:
x - y

array([[-2, -2],
       [-1, -1]])

In [75]:
np.subtract(x,y)

array([[-2, -2],
       [-1, -1]])

In [76]:
np.multiply(x,y)

array([[ 3,  8],
       [ 6, 12]])

In [78]:
np.divide(x,y)

array([[0.33333333, 0.5       ],
       [0.66666667, 0.75      ]])

In [81]:
np.power(x,2)

array([[1, 4],
       [4, 9]], dtype=int32)

In [82]:
x

array([[1, 2],
       [2, 3]])

In [83]:
x

array([[1, 2],
       [2, 3]])

In [84]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]])

In [85]:
x +b

ValueError: operands could not be broadcast together with shapes (2,2) (2,12) 

# Indexing over numpy array

In [93]:
b.resize(6,4)

In [94]:
b

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

In [95]:
b.shape

(6, 4)

In [96]:
# indexing works directly on row
b[0]

array([100,   1,   2,   3])

In [97]:
b[2]

array([ 8,  9, 10, 11])

In [98]:
b[-1]

array([20, 21, 22, 23])

In [100]:
b

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

In [101]:
b[-2]

array([16, 17, 18, 19])

#### if we want to access internal elements present in the row

In [102]:
b[0]

array([100,   1,   2,   3])

In [103]:
b[0,0]

100

In [104]:
b[0,-1]

3

In [106]:
b[0][-1]

3

In [107]:
id(b)

2782987384464

In [109]:
#lets try to change values from b
b[0,0]

100

In [110]:
b[0,0] = 0

In [111]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [112]:
id(b)

2782987384464

#### after changing data , id is nt changing and changes persist in the same object
# hence numpy array is mutable

### slicing

In [114]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [115]:
b[:] #dfault slicing works on rows

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [116]:
b[2:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [117]:
b[::-1]

array([[20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [118]:
b[-2:]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [120]:
# fetch middle rows
#[ 8,  9, 10, 11],
#[12, 13, 14, 15]
b[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
"""
[ 0,  1,  2,  3]
[ 8,  9, 10, 11]
[16, 17, 18, 19]
"""
b[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [125]:
"""
[ 0,  1,  2,  3]
[ 8,  9, 10, 11],
[12, 13, 14, 15],
"""
b[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])